name: Publish on New Tag
on:
  push:
    tag:
      - 'v*'

jobs:
  master:
    name: publish
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: node common/scripts/install-run-rush.js update

      - name: build and publish
        run: |
          cd bodhi
          rushx build
          rushx publish --access public --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
