name: Build and Release on New Tag
on:
  push:
    tags:
      - 'v*'

jobs:
  master:
    strategy:
      matrix:
        step: ['build:release']
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.step }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn
          cd bodhi/
          yarn ${{ matrix.step }}

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
