name: Build and Release on New Tag
on:
  push:
    tags:
      - 'v*'

jobs:
  master:
    name: build and publish
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd bodhi/
          yarn
          yarn build
          yarn publish

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
